### ISSUE TITLE
Analyze results by query

### ISSUE THREAD

**Issue by qinghao1** [qinghao1/terrier-core#31]
what kind of queries do the best performing approach perform on well, which one not? And once you know which topics are poorly performing, can you speculate why and - potentially - what other retrieval approaches (or maybe a combination of different IR technologies we covered in the lecture) could be a better fit for the task at hand

**Comment by qinghao1** [comment]
can turn on results per query in terrier

**Comment by limyongsong** [comment]
Did the code for the sorting. Will try to do the report part after all model edits are done and evaluated.
